CREATE TABLE ITEM
(
    ID                 NUMBER         NOT NULL,
    NAME               VARCHAR2(255)  NOT NULL,
    TYPE               VARCHAR2(100)  NOT NULL,
    QUANTITY           NUMBER         NOT NULL,
    RECOMMENDED_SEASON VARCHAR2(100)  NOT NULL,
    WEIGHT             NUMERIC(19, 3) NOT NULL,
    CONSTRAINT PK_ITEM_ID PRIMARY KEY (ID)
);

CREATE TABLE BACKPACK
(
    ID             NUMBER         NOT NULL,
    BAG_SIZE       VARCHAR2(100)  NOT NULL,
    CURRENT_WEIGHT NUMERIC(19, 3) NOT NULL,
    CONSTRAINT PK_BAG_ID PRIMARY KEY (ID)
);

CREATE TABLE ITEM_LIST
(
    BACKPACK_ID NUMBER NOT NULL,
    ITEM_ID     NUMBER NOT NULL,
    CONSTRAINT FK_BACKPACK_ID FOREIGN KEY (BACKPACK_ID) REFERENCES BACKPACK (ID),
    CONSTRAINT FK_ITEM_ID FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ID)
);

CREATE TABLE TRIP
(
    ID          NUMBER NOT NULL,
    DISTANCE    NUMBER NOT NULL,
    SEASON      VARCHAR2(100) NOT NULL,
    BACKPACK_ID NUMBER NOT NULL,
    CONSTRAINT FK_BP_ID FOREIGN KEY (BACKPACK_ID) REFERENCES BACKPACK (ID),
    CONSTRAINT PK_TRIP_ID PRIMARY KEY (ID)
);

CREATE SEQUENCE TRIP_SEQ;
CREATE SEQUENCE BAG_SEQ;
CREATE SEQUENCE ITEM_SEQ;