INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (1, 'Water', 'CONSUMABLE', 0, 1.000, 'ALL');
INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (2, 'Protein bar', 'CONSUMABLE', 0, 0.100, 'ALL');
INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (3, 'Dried meat', 'CONSUMABLE', 0, 0.100, 'ALL');
INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (4, 'Various nuts', 'CONSUMABLE', 0, 0.150, 'ALL');
INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (5, 'Camping knife', 'UTILITY', 0, 0.200, 'ALL');
INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (6, 'Camping kettle', 'UTILITY', 0, 0.400, 'ALL');
INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (7, 'Camping utensils', 'UTILITY', 0, 0.200, 'ALL');
INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (8, 'Sleeping bag', 'UTILITY', 0, 1.000, 'ALL');
INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (9, 'Firestarter', 'UTILITY', 0, 0.050, 'ALL');
INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (10, 'Socks', 'CLOTHING', 0, 0.020, 'SUMMER');
INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (11, 'Warm socks', 'CLOTHING', 0, 0.040, 'WINTER');
INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (12, 'Hiking boots', 'CLOTHING', 0, 0.850, 'SUMMER');
INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (13, 'Warm winter boots', 'CLOTHING', 0, 1.250, 'WINTER');
INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (14, 'Gloves', 'CLOTHING', 0, 0.120, 'WINTER');
INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (15, 'Warm hat', 'CLOTHING', 0, 0.320, 'WINTER');
INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (16, 'Map', 'UTILITY', 0, 0.190, 'ALL');
INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (17, 'GPS', 'UTILITY', 0, 0.260, 'ALL');
INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (18, 'Compass', 'UTILITY', 0, 0.120, 'ALL');
INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (19, 'First aid kit', 'FIRST_AID', 0, 0.500, 'ALL');
INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (20, 'Matches', 'UTILITY', 0, 0.050, 'ALL');
INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (21, 'Medications', 'FIRST_AID', 0, 0.050, 'ALL');
INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (22, 'Sun cream', 'FIRST_AID', 0, 0.350, 'SUMMER');
INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (23, 'Toilet paper', 'CONSUMABLE', 0, 0.100, 'ALL');
INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (24, 'Umbrella', 'UTILITY', 0, 0.200, 'FALL');
INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (25, 'Summer cap', 'CLOTHING', 0, 0.050, 'SUMMER');
INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (26, 'Personal documents', 'OTHER', 0, 0.050, 'ALL');
INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (27, 'Mobile phone', 'UTILITY', 0, 0.200, 'ALL');
INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (28, 'Power bank', 'UTILITY', 0, 0.250, 'ALL');
INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (29, 'Bandages', 'FIRST_AID', 0, 0.050, 'ALL');
INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (30, 'Pants', 'CLOTHING', 0, 0.350, 'WINTER');
INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (31, 'Shorts', 'CLOTHING', 0, 0.150, 'SUMMER');
INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (32, 'Shirt', 'CLOTHING', 0, 0.200, 'WINTER');
INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (33, 'T-Shirt', 'CLOTHING', 0, 0.100, 'SUMMER');
INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (34, 'Jacket', 'CLOTHING', 0, 0.400, 'FALL');
INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (35, 'Raincoat', 'CLOTHING', 0, 0.800, 'FALL');
INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (36, 'Waterproof jacket', 'CLOTHING', 0, 1.300, 'SPRING');
INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (37, 'Wallet', 'OTHER', 0, 0.150, 'ALL');
INSERT INTO ITEM(ID, NAME, TYPE, QUANTITY, WEIGHT, RECOMMENDED_SEASON)
VALUES (38, 'Tent', 'OTHER', 0, 5.000, 'ALL');